import { StyleSheet } from 'react-native';

const StyleStudy = StyleSheet.create({
    Body: {
        margin: 20,
        borderWidth: 1,
        borderColor: 'red',
    },
    item: {
        padding: 15,
        borderBottomWidth: 1,
        borderWidth: 1,
        borderColor: '#da91a4',
        height: 280,
        margin: 30,
    },
    searchBarContainer: {
        backgroundColor: 'transparent',
        borderBottomColor: 'transparent',
        borderTopColor: 'transparent',
        paddingHorizontal: 10,
        marginVertical: 10,
    },
    searchBarInput: {
        backgroundColor: '#fff',
    },
    DrawerButton: {
        position: 'absolute',
        right: 20,
        bottom: 70,
    },
    modalContainerMenu: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'space-around'
    },
    modalMenu: {
        backgroundColor: '#f3e5e4',
        padding: 10,
        borderTopLeftRadius: 10,
        borderBottomLeftRadius: 10,
        elevation: 5,
        height: 800,
        marginLeft: 200,
        
    },
    modalContainer: {
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        height: '100%',
        justifyContent: 'center',
    },
    modalInput: {
        backgroundColor: 'white',
        borderRadius: 10,
        elevation: 5,
        height: '60%',
        borderWidth: 1,
        margin: 30,
        borderColor: '#da91a4',
    },
    modalTextInput: {
        borderWidth: 1,
        borderColor: '#da91a4',
        alignSelf: 'center',
        width: 250,
        marginBottom: 20,
        padding: 5
    },
    modalTextInput2: {
        borderWidth: 1,
        borderColor: '#da91a4',
        alignSelf: 'center',
        width: 250,
        marginBottom: 20,
        padding: 5,
        flexDirection:'row',
    },
    modalItemText: {
        fontSize: 20,
        fontWeight: "bold",
        alignSelf: 'center',
        color: '#f3e5e4',
        textAlign: 'center'
    },
    modalItemText2: {
        fontSize: 20,
        fontWeight: "bold",
        alignSelf: 'center',
        color: '#da91a4',
        margin:20,
        textAlign: 'center'
    },
    modalItemText3: {
        fontSize: 18,
        marginBottom: 8,
        textAlign:'center'
    },
    modalFuntion: {
        backgroundColor: '#da91a4',
        margin: 20,
        padding: 10,
        borderRadius: 15
    },
    modalInfo: {
        alignItems: 'center',
        padding:10,
        borderWidth: 2,
        borderColor:'#da91a4',
        borderRadius: 20,
    },
    modalDetail: {
        backgroundColor: 'white',
        padding: 10,
        borderRadius: 10,
        elevation: 5,
        alignItems: 'center',
        width: 300,
        height:500,
    },
    modalContainer2: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    closeButton: {
        marginTop: 20,
        backgroundColor: '#da91a4',
    },
    closeButton2: {
        marginTop: 20,
        backgroundColor: '#da91a4',
        marginRight:10,
    },
    buttonDetail: {
        alignItems: 'center',
        position: 'absolute',
        top: 210,
        alignSelf: 'center',
    },
    buttonDetail2: {
        alignItems: 'center',
        position: 'absolute',
        top: 210,
        alignSelf: 'center',
        flexDirection: 'row',
    },
    Search: {
        backgroundColor: '#f3e5e4',
        margin: 15,
        marginBottom: 0,
        borderWidth: 1,
        borderColor:'#da91a4',
    },
    scrollContainer: {
        maxHeight: '90%', 
    },
    addButton: {
        borderWidth: 1,
        borderColor:'#da91a4',
        alignSelf: 'center',
    },
    addSButton: {
        borderWidth: 1,
        borderColor:'#da91a4',
        alignSelf: 'center',
        backgroundColor: '#fff',
        marginTop:10,
    },
    AddButtonStudent: {
        borderWidth: 1,
        borderTopWidth:0,
        borderColor: '#da91a4',
        marginLeft: 40.5,
        marginRight: 40,
        bottom: 20,
        paddingTop: 20,
        paddingBottom:20,
    },
    textOriginal: {
        backgroundColor:'#da91a4',
        borderWidth: 1,
        borderColor:'#da91a4',
        color: '#f3e5e4',
        fontSize: 15,
        padding: 10,
        paddingBottom:0,
        margin: 40,
        marginTop:10,
        marginBottom: 0,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    textOriginal2: {
        backgroundColor:'#da91a4',
        borderWidth: 1,
        borderColor:'#da91a4',
        color: '#f3e5e4',
        fontSize: 15,
        padding: 10,
        paddingTop:0,
        margin: 40,
        marginTop:0,
        marginBottom: 0,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    textOriginal4: {
        backgroundColor:'#fff',
        borderWidth: 1,
        borderBottomWidth:0,
        borderColor:'#da91a4',
        color: '#da91a4',
        fontSize: 15,
        padding: 10,
        paddingBottom:0,
        margin: 40,
        marginTop:10,
        marginBottom: 0,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    textOriginal3: {
        backgroundColor:'#fff',
        borderWidth: 1,
        borderTopWidth: 0,
        borderBottomWidth:0,
        borderColor:'#da91a4',
        color: '#da91a4',
        fontSize: 15,
        padding: 10,
        paddingTop:0,
        margin: 40,
        marginTop:0,
        marginBottom: 0,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    loadingContainer: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.3)',
    },
});

export default StyleStudy;
